num_1 = input("Number One: ")
num_2 = input("Number Two: ")
sum = int(num_1) + int(num_2)
print("Summed:{0}".format(sum))
sub = int(num_1) - int(num_2)
print("Subtracted:{0}".format(sub))
mult = int(num_1) * int(num_2)
print("Multiplied:{0}".format(mult))
div = float(num_1) / float(num_2)
print("Divided:{0}".format(div))